const PDFDocument = require("pdfkit");

class PDFService {
  generateEquipmentReport(equipment, stream) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: "LETTER",
          margins: { top: 50, bottom: 50, left: 50, right: 50 },
        });

        doc.pipe(stream);

        // Header
        doc
          .fontSize(20)
          .font("Helvetica-Bold")
          .text("EQUIPMENT INSPECTION REPORT", { align: "center" })
          .moveDown();

        doc
          .fontSize(12)
          .font("Helvetica")
          .text(`Date: ${new Date().toLocaleDateString()}`, { align: "right" })
          .moveDown(2);

        // Equipment Details Section
        this.addSection(doc, "EQUIPMENT DETAILS");

        const details = [
          { label: "Equipment Number", value: equipment.cr164_equipmentnumber },
          { label: "Description", value: equipment.cr164_equipmentdescription },
          { label: "Location", value: equipment.cr164_location },
          { label: "Manufacturer", value: equipment.cr164_manufacturer },
          { label: "Model", value: equipment.cr164_model },
          { label: "Serial Number", value: equipment.cr164_serialnumber },
          { label: "Flow Range", value: equipment.cr164_flowrange },
          {
            label: "Status",
            value:
              equipment[
                "statecode@OData.Community.Display.V1.FormattedValue"
              ] || "N/A",
          },
        ];

        details.forEach((detail) => {
          this.addField(doc, detail.label, detail.value);
        });

        doc.moveDown(2);

        // Inspection Section
        this.addSection(doc, "INSPECTION CHECKLIST");

        const checklist = [
          "Visual inspection completed",
          "Calibration verified",
          "Connections checked",
          "Safety systems tested",
          "Documentation updated",
        ];

        checklist.forEach((item) => {
          doc
            .fontSize(10)
            .text("☐ " + item)
            .moveDown(0.5);
        });

        doc.moveDown(2);

        // Notes Section
        this.addSection(doc, "NOTES");

        // Create a box for notes
        const notesY = doc.y;
        doc.rect(50, notesY, 512, 100).stroke();
        doc.moveDown(8);

        // Signature Section
        doc.moveDown(2);
        this.addSection(doc, "SIGNATURES");

        const signatureY = doc.y;
        const columnWidth = 240;

        // Inspector Signature
        doc.fontSize(10).text("Inspector:", 50, signatureY);
        doc
          .moveTo(50, signatureY + 40)
          .lineTo(50 + columnWidth, signatureY + 40)
          .stroke();
        doc
          .fontSize(8)
          .text("Signature", 50, signatureY + 45)
          .text("Date: _______________", 50, signatureY + 60);

        // Supervisor Signature
        doc.fontSize(10).text("Supervisor:", 320, signatureY);
        doc
          .moveTo(320, signatureY + 40)
          .lineTo(320 + columnWidth, signatureY + 40)
          .stroke();
        doc
          .fontSize(8)
          .text("Signature", 320, signatureY + 45)
          .text("Date: _______________", 320, signatureY + 60);

        // Footer
        doc
          .fontSize(8)
          .font("Helvetica-Oblique")
          .text("Generated by Indus Control System", 50, doc.page.height - 50, {
            align: "center",
          });

        doc.end();

        doc.on("finish", () => {
          resolve();
        });

        doc.on("error", (err) => {
          reject(err);
        });
      } catch (error) {
        reject(error);
      }
    });
  }

  addSection(doc, title) {
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor("#333333")
      .text(title)
      .moveDown(0.5);

    doc
      .moveTo(50, doc.y)
      .lineTo(562, doc.y)
      .strokeColor("#666666")
      .lineWidth(1)
      .stroke();

    doc.moveDown();
    doc.fillColor("#000000");
  }

  addField(doc, label, value) {
    const y = doc.y;

    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .text(label + ":", 50, y, { width: 150, continued: false });

    doc.font("Helvetica").text(value || "N/A", 210, y, { width: 352 });

    doc.moveDown(0.5);
  }
}

module.exports = PDFService;
